### PR TITLE
Added callback on send method

### PR DESCRIPTION
**Pull request by tomav**

### CODE REVIEW

**Comment by tomav** [comment]
Hmm, no Travis CI?

**Comment by mattpage** [comment]
@tomav Should not callback should be called on error as well?

**Comment by tomav** [comment]
Or perhaps differentiate both callbacks with `onerror` and `onsuccess`instead of `done`?
What do you think.

**Comment by mattpage** [comment]
I think it should be consistent with the done callback in query

https://github.com/flightstats/node-insights/blob/master/index.js#L337

**Comment by tomav** [comment]
Done.

**Comment by mattpage** [comment]
Looks good to me. @cmwood ?

**Comment by tomav** [comment]
Hi @cmwood let me know, thanks!

**Comment by tomav** [comment]
Hi guys, any update on that? Thank you!

**Comment by tomav** [comment]
Hi, can I have an answer?
Project is still maintained?

**Comment by cmwood** [comment]
@tomav My apologies for such a long delay. Yes, maintained. Merging. 👍

**Comment by cmwood** [comment]
@mattpage Back to you for publication. Perhaps add me as a collaborator?

**Comment by mattpage** [comment]
published! I added you as collab @cmwood

**Pull request merged**
