### PR TITLE
support nrql construction from a javascript object

### PR DESCRIPTION
**Pull request by cirne**
Hey! Lew Cirne here, founder and CEO at New Relic. Love that you are doing an npm package for Insights. I began some work on something similar but never published.  I frequently create queries of simple JS objects, similar to the model introduced by Rails ActiveRecord.  Hope you like it!

Cheers!

/cc @wraithan @groundwater

### CODE REVIEW

**Comment by mattpage** [comment]
This is cool. 
I'll go ahead and merge it despite the fact that you hate semicolons :P
Thanks!

**Comment by cirne** [comment]
Hah my bad. I actually like semicolons; I just sometimes forget, and I blame @groundwater as an enabler.  Too much time in Ruby.

**Comment by mattpage** [comment]
No worries. That's published as 1.0.7.
The test coverage shows that:
```
  if(params.compare) {
    nrql += " COMPARE WITH " + params.compare;
  }
```
is not being tested. 

I'm not familiar with 'compare with', is there a simple test param for that?

If you are curious, you can generate the test coverage like so:

```
npm install istanbul -g
grunt coverage
open ./coverage/lcov-report/index.html #or however you want to open in a browser
```

**Comment by groundwater** [comment]
What semicolons :hear_no_evil: :see_no_evil:

:smiley:

**Pull request merged**
