### PR TITLE
custom logger could be passed

### PR DESCRIPTION
**Pull request by wtfil**
Hi!

Thank you for awesome library, but I have only one issue: this library put something to stdout/stderr. Unfortunately it breaking our logging system:( 

That's way I've made this PR. The main idea is to have ability to pass own logger which will fulfill product requirements.

Backward compatibility, of course,  guaranteed

### CODE REVIEW

**Comment by breedx2** [comment]
Looks fine to me, and my group can likely use this as well.

**Comment by wtfil** [comment]
@breedx2 good!
Any plans about this PR?:)

**Comment by mattpage** [comment]
Yup, this is good stuff. Merged.

**Comment by mattpage** [comment]
@wtfil thanks for the new feature. I just published your change to version 1.08

**Comment by wtfil** [comment]
Thanks :)

**Pull request merged**
